name: DotNet multiple version testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: ['ubuntu-24.04', 'ubuntu-22.04','ubuntu-20.04', 'ubuntu-latest']
       dotnet-version: ['6.x','7.0']
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet # ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@remove-fallback-cdn-logic-v3
        with:
          dotnet-version:  ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
