name: issue565

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Test Dotnet 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '2.2.402'
