name: Install .NET SDKs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 9.0 SDK and ASP.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install .NET 8.0 SDK and ASP.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        include-prerelease: 'false'

    - name: Verify .NET SDKs
      run: dotnet --info
