name: 620 actions/cachePR testing 
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-22.04, ubuntu-latest, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up dotnet
        uses: mahabaleshwars/setup-dotnet@upgrade-cache-for-v3
        with:
          dotnet-version: '7.x'
          cache: true

      - name: Restore dependencies
        run: dotnet restore

     
