name: Install .NET SDKs

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: test setup dotnet
      id: testdotnet
      uses: actions/setup-dotnet@c7e7147fd3e41056e75a761416c06f5fa781b5fb
      with:
          dotnet-version: '7'
