name: .NET Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Set DOTNET_INSTALL_DIR and update PATH
        run: |
          echo "DOTNET_INSTALL_DIR=$HOME/.dotnet" >> $GITHUB_ENV
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet
          DOTNET_ROOT: $HOME/.dotnet

      - name: Display .NET version
        run: dotnet --info

