name: dotnet package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Set DOTNET_ROOT for dotnet 9
        run: echo "DOTNET_ROOT=/usr/lib/dotnet" >> $GITHUB_ENV
      - name: Display dotnet version
        run: dotnet --info

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Set DOTNET_ROOT for dotnet 8
        run: echo "DOTNET_ROOT=/usr/lib/dotnet" >> $GITHUB_ENV
      - name: Display dotnet version
        run: dotnet --info
