name: issue565

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
   
    steps:
    - uses: actions/checkout@v4
    - name: Test Dotnet before
      run: |
        dotnet --version
        dotnet --info
        dotnet --list-runtimes
        dotnet --list-sdks
        whereis dotnet
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
