name: dotnet package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Add dotnet 9 to PATH
        run: echo "/usr/lib/dotnet" >> $GITHUB_PATH
      - name: Display dotnet version
        run: dotnet --info
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Add dotnet 8 to PATH
        run: echo "/usr/lib/dotnet" >> $GITHUB_PATH
      - name: Display dotnet version
        run: dotnet --info
