name: issue540

on:
  workflow_dispatch:

jobs:
  Test_Dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Before setup
      run: dotnet --info
      
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      env:
        DOTNET_ROOT: /usr/share/dotnet/dotnet9
      
    - name: After .NET 9
      run: dotnet --info
      env:
        DOTNET_ROOT: /usr/share/dotnet/dotnet9

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
      env:
        DOTNET_ROOT: /usr/share/dotnet/dotnet8
        
    - name: After .NET 8
      run: dotnet --info
      env:
        DOTNET_ROOT: /usr/share/dotnet/dotnet8
