name: Switch to Native Jammy Packages

on: 
  workflow_dispatch:

jobs:
  setup_dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Remove all .NET packages
        run: |
          sudo apt remove --purge -y dotnet*
          sudo apt remove --purge -y aspnetcore*

      - name: Delete PMC repository
        run: sudo rm /etc/apt/sources.list.d/microsoft-prod.list || true

      - name: Update APT
        run: sudo apt update

      - name: Install .NET SDK 6.0
        run: sudo apt install -y dotnet-sdk-8.0

      - name: Verify .NET Installation
        run: dotnet --info
