# workflow.yml
name: Test #141

on: 
 workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0'
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build




