name: Install .NET SDKs

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
   
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
  
