name: Switch to Native Jammy Packages

on: 
  workflow_dispatch:

jobs:
  setup_dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Remove .NET SDKs
        run: |
          sudo apt-get remove --purge -y dotnet-sdk-*
          sudo apt-get autoremove -y
     


      - name: Install .NET SDK 8.0
        run: sudo apt install -y dotnet-sdk-8.0

      - name: Verify .NET Installation
        run: dotnet --info
