name: issue540

on:
  workflow_dispatch:

jobs:
  Test_Dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: | 
          3.1.x
          5.0.x
    - name: After dotnet 8
      run: dotnet --info
