name: dotnet package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          install-dir: '/usr/lib/dotnet/sdk'
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          install-dir: '/usr/lib/dotnet/sdk'
      - name: Display dotnet version
        run: dotnet --info
