name: issue540

on:
  workflow_dispatch:

jobs:
  Test_Dependabot:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: After dotnet 8
      run: dotnet --info
