name: .NET Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Set DOTNET_ROOT and update PATH
        run: |
          echo "DOTNET_ROOT=/usr/lib/dotnet" >> $GITHUB_ENV
          echo "/usr/lib/dotnet" >> $GITHUB_PATH

      - name: Manually install .NET 9.0.x SDK
        run: |
          mkdir -p /usr/lib/dotnet
          wget https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-rc.2.24474.11/dotnet-sdk-9.0.100-rc.2.24474.11-linux-x64.tar.gz
          tar -C /usr/lib/dotnet -xzf dotnet-sdk-9.0.100-rc.2.24474.11-linux-x64.tar.gz
        env:
          DOTNET_ROOT: /usr/lib/dotnet

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        env:
          DOTNET_ROOT: /usr/lib/dotnet

      - name: Display .NET version
        run: dotnet --info

     
