name: Install .NET SDKs

on: [push]

jobs:
  build:
    runs-on: self-hosted
    env:
      HTTP_PROXY: http://proxy.example.com:8080
      HTTPS_PROXY: https://proxy.example.com:8080
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
  
