name: issue852

on:
 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-node-fork@test-composite
        with:
          node-version-file: ${{ github.action_path }}/.nvmrc
