name: Install .NET from Jammy Feed

on: [push]

jobs:
  setup_dotnet:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Before setup
        run: dotnet --info
