name: Install .NET Manually

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set DOTNET_INSTALL_DIR and update PATH
      run: |
        echo "DOTNET_INSTALL_DIR=$HOME/.dotnet" >> $GITHUB_ENV
        echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
        echo "$HOME/.dotnet" >> $GITHUB_PATH

    - name: Install .NET 7.0
      run: |
        mkdir -p $HOME/.dotnet
        wget https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-7.0.100-linux-x64-binaries
        tar -zxf sdk-7.0.100-linux-x64-binaries -C /usr/lib/dotnet

    - name: Install .NET 8.0
      run: |
        mkdir -p $HOME/.dotnet
        wget https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-8.0.100-linux-x64-binaries
        tar -zxf sdk-8.0.100-linux-x64-binaries -C /usr/lib/dotnet
