name: Install .NET SDKs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create symbolic links for .NET SDKs
      run: |
        mkdir -p /usr/share/dotnet
        ln -s  /usr/share/dotnet $HOME/.dotnet

    - name: Install .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Verify .NET SDKs
      run: dotnet --info
