name: Install .NET from Jammy Feed

on: [push]

jobs:
  setup_dotnet:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Remove existing .NET packages
        run: |
          sudo apt remove --purge -y dotnet*
          sudo apt remove --purge -y aspnetcore*

      - name: Delete PMC repository
        run: sudo rm /etc/apt/sources.list.d/microsoft-prod.list || true

      - name: Update APT
        run: sudo apt update

      - name: Install .NET SDK from Jammy feed
        run: sudo apt install -y dotnet-sdk-6.0

      - name: Verify .NET Installation
        run: dotnet --info
