name: Tesing141

on: 
 workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
        DOTNET_INSTALL_DIR: ${{ github.workspace }}/dotnet
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "9.0"
   
   
   



