name: Cleanup .NET SDKs

on: [push]

jobs:
  cleanup_dotnet:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove all .NET SDK and runtime versions
        run: dotnet --info
