name: testing#523

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - run: dotnet workload --info
      # - run: dotnet workload install aspire
          
