name: Test Setup Dotnet Action Publish nuget.org
on:
  push:
    branches:
      - setup-dotnet
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_AUTH_TOKEN}}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
      

