name: Test167

on:
  workflow_dispatch:

jobs:
  multi-source-test:
    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:
      - uses: actions/checkout@v4

      # Setup .NET Core (default NuGet.org source is included automatically)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Add GitHub Packages Source (use your username in the URL)
      - name: Add GitHub Packages Source
        shell: bash
        run: dotnet nuget add source https://nuget.pkg.github.com/gowriduragd/index.json --name github --username ${{ github.actor }} --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text

      # Restore NuGet packages (from all configured sources)
      - name: Restore NuGet packages
        run: dotnet restore ./MyApp/MyApp.csproj

      # Optionally test a build
      - name: Build
        run: dotnet build ./MyApp/MyApp.csproj
