name: Test167

on:
  workflow_dispatch:

jobs:
  multi-source-test:
    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:
      - uses: actions/checkout@v4

      - name: Add NuGet.Config with multiple sources
        run: |
          cat > NuGet.Config <<EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
              <add key="github" value="https://nuget.pkg.github.com/gowridurgad/index.json" />
            </packageSources>
          </configuration>
          EOF

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          source-url: |
            https://api.nuget.org/v3/index.json
            https://nuget.pkg.github.com/gowriduragd/index.json

      - name: Restore NuGet packages
        run: dotnet restore ./MyApp/MyApp.csproj
        env:
          NuGetPackageSourceCredentials_github: Username=${{ github.actor }};Password=${{ secrets.TOKEN_GITHUB  }}

      # Optionally test a build
      - name: Build
        run: dotnet build
        working-directory: ./MyApp
        env:
          NuGetPackageSourceCredentials_github: Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}
