name: testing707

on:

  workflow_dispatch:


jobs:
  test:
    # strategy:
    #  matrix:
    #     # os: [ubuntu-latest, macos-latest, windows-latest] 
        
    runs-on: ubuntu-latest
    

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v5

  
    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: 'Restore packages'
      run: dotnet restore MyApp/MyApp.csproj

    - name: Test
      run: dotnet test MyApp/MyApp.csproj
